# Copyright 2025 LSDAF
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 🗑️ Delete Docker Image

run-name: Delete Docker image with tag ${{ github.event.inputs.image_tag }}

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag of the image to delete (e.g., a Git SHA)'
        required: true
        type: string
      github_token:
        description: 'GitHub Personal Access Token with read:org permissions'
        required: true
        type: string

jobs:
  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 🔒 Check user permissions
        id: check_user_permissions
        run: |
          source ./scripts/user_permissions.sh
          check_user_permissions "${{ github.event.inputs.github_token }}" || exit 1

      - name: 🔐 Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.event.inputs.github_token }}

      - name: 🔒 Check if image exists
        id: check_docker_image
        run: |
          source ./scripts/docker_utils.sh
          check_docker_image_exists "ghcr.io/lsdaf/lsadf_api:${{ github.event.inputs.image_tag }}" \
            "Image with tag ${{ github.event.inputs.image_tag }} exists. Proceeding with deletion." \
            "::error::Image with tag ${{ github.event.inputs.image_tag }} does not exist." || exit 1

      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          # NOTE: at now only orgs is supported
          owner: LSDAF
          name: lsadf_api
          # NOTE: using the provided GitHub token
          token: ${{ github.event.inputs.github_token }}
          tag: ${{ github.event.inputs.image_tag }}
